# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c38ca63e874f14e89247081b54b128e3c7def7ffb5d539b5ee25a2589b14c4d1890a2abafd0d66c1bc2fda4fb5b4cdc506caa831901bdf6e426c91643230f7b3

test:
  secret_key_base: cd360ee74f386d03da91b9fa3db679e37895560bd0a04caad697f7195e5d93d0916f55c45ae9ff753a82e9e6e9ee6865f3c508daa4bf21107e83e98e508a9f7e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
